{
 "title": "Starlink Statistics",
 "description": "Dishy Statistics",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "InfluxDB DataSource", "query": "starlinkstats" },
   {
    "name": "TBL_STATS",
    "label": "Table name for Statistics",
    "query": "spacex.starlink.user_terminal.status"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" }
      ],
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PoP Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max obstruction time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "obstruction_duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "query": "SELECT \"pop_ping_latency_ms\" FROM \"spacex.starlink.user_terminal.history\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "pop_ping_drop_rate" ], "type": "field" },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.power",
     "select": [
      [
       { "params": [ "latest_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Obstructions Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "fraction_obstructed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dishy System Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"state\" AS \"State\", \"currently_obstructed\" AS \"Obstructed\", \"alert_unexpected_location\" AS \"Unexpected Location\", \"alert_thermal_throttle\" AS \"Temp Throttled\", \"alert_thermal_shutdown\" AS \"Temp Shutdown\", \"alert_motors_stuck\" AS \"Motors Stuck\", \"software_version\" AS \"Software Version\", \"alert_install_pending\" AS \"Install Pending\",  \"alert_slow_ethernet_speeds\" AS \"Slow Speed\", \"alert_mast_not_near_vertical\" AS \"Mast Not Vertical\", \"alert_is_heating\" AS \"Heating\", \"alert_roaming\" AS \"Roaming\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "currently_obstructed" ], "type": "field" },
       { "params": [ "Obstructed" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_unexpected_location" ], "type": "field" },
       { "params": [ "Unexpected Location" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_thermal_throttle" ], "type": "field" },
       { "params": [ "Temp Throttled" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_thermal_shutdown" ], "type": "field" },
       { "params": [ "Temp Shutdown" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_motors_stuck" ], "type": "field" },
       { "params": [ "Motors Stuck" ], "type": "alias" }
      ],
      [
       { "params": [ "software_version" ], "type": "field" },
       { "params": [ "Software Version" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_slow_ethernet_speeds" ], "type": "field" },
       { "params": [ "Slow Speed" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_mast_not_near_vertical" ], "type": "field" },
       { "params": [ "Mast Not Vertical" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_is_heating" ], "type": "field" },
       { "params": [ "Heating" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_roaming" ], "type": "field" },
       { "params": [ "Roaming" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}